language: php

# list any PHP version you want to test against
php:
  # Polr only supports versions > 5.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
